services:
  service:
      volumes:
        - ./:/app
        - /tmp/.X11-unix:/tmp/.X11-unix
        - ~/.Xauthority:/root/.Xauthority
        - ~/.bash_history:/home/eric/.bash_history
        - ~/.gitconfig:/etc/gitconfig
        - ~/.ssh:/home/eric/.ssh
        - /mnt/wslg:/mnt/wslg
        # initial data
        - /mnt/shape_data:/mnt/slow/shape_data
        # own data
        - /mnt/smb/shapenetcorev2-source:/mnt/slow/shapenetcorev2-source
        # new shapnetcorev2
        - /mnt/smb/shapenetcorev2-h5:/mnt/slow/shapenetcorev2-h5
        
      runtime: nvidia
      network_mode: "host"
      # build:
      #   dockerfile: Dockerfile
      #   context: .
      # image: ${REGISTRY_URL}/keypoint:1.0
      image: keypoint_diffuser:latest

      tty: true
      stdin_open: true
      privileged: true
      restart: unless-stopped

      deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: all
                capabilities: [gpu, compute, utility, graphics]
      environment:
        - DISPLAY=$DISPLAY
        - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}
        - NVIDIA_VISIBLE_DEVICES=all
