# Package ######################################################################

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "keypoint_diffuser"
version = "0.1.0"
description = "Keypoint Diffuser Project"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10"
dependencies = [
    "PyYAML==6.0",
    "torch",
    "torchvision",
    "einops==0.8.1",
    "tqdm==4.64.1",
    "scipy==1.11.4",
    "wandb==0.19.9",
    "addict==2.4.0",
    "tensorboardX==2.6.2.2",
    "open3d==0.18.0",
    "timm",
    "ConfigArgParse==1.4",
    "pytorch3d==0.7.8",
    "torch-scatter",
    "spconv-cu116",
]


# Linters and Test tools #######################################################
[tool.ruff]
# https://beta.ruff.rs/docs/settings/
extend-select = ["C4", "SIM", "TCH"]
show-fixes = true
# Same as Black.
line-length = 100
# Assume Python 3.10
target-version = "py310"

ignore = [
    "ARG001", "ARG002",
    "E402",
    "FBT002", "FBT003",
    "N802", "N806", "N812", "NPY002",
    "PLR0913", "SIM115",
    "S101", "PLR2004",
    "B905", "A002", "N803", "N801", "PD011",
    "E741", "A001", "FBT001", "S608"

]

select = [
    "A",
    "ARG",
    "B",
    "C4",
    "C90",
    "E",
    "ERA",
    "F",
    "FBT",
    "ICN",
    "I",
    "ISC",
    "N",
    "NPY",
    "PD",
    "PGH",
    "PIE",
    "PLE",
    "PLR",
    "Q",
    "RUF",
    "S",
    "SIM",
    "T",
    "UP",
    "W",
]

[tool.ruff.mccabe]
# Unlike Flake8, default to a complexity level of 10.
max-complexity = 30

[tool.ruff.isort]
lines-after-imports = 2
extra-standard-library = ["typing_extensions"]

[tool.ruff.pylint]
max-statements = 150
max-branches=25
max-args=15


[tool.black]
line-length = 88

[tool.pyright]
include = ["posggym/**"]
exclude = ["**/node_modules", "**/__pycache__"]
strict = []

typeCheckingMode = "basic"
pythonVersion = "3.10"
pythonPlatform = "All"
enableTypeIgnoreComments = true

# This is required as the CI pre-commit does not download the module (i.e. numpy, pygame, box2d)
#   Therefore, we have to ignore missing imports
reportMissingImports = "none"
# Some modules are missing type stubs, which is an issue when running pyright locally
reportMissingTypeStubs = false
# For warning and error, will raise an error when
reportInvalidTypeVarUse = "none"

reportGeneralTypeIssues = "none" # -> commented out raises 489 errors
# reportUntypedFunctionDecorator = "none"  # -> pytest.mark.parameterize issues

reportPrivateUsage = "warning"
reportUnboundVariable = "warning"
reportOptionalOperand = "warning"

[tool.pytest.ini_options]
filterwarnings = [
	# Tensorboard warnings
	"ignore::DeprecationWarning:tensorboard",
]
