name: airplane-8kpt

category: 02691156
split: train

# mesh_dir: /mnt/storage/
# points_dir: /mnt/storage/
# split_file: /mnt/storage/shapenet_split/all.csv
# log_dir: /mnt/storage/keypoints/logs


mesh_dir: /app/data/shapenet/shape_data
points_dir: /app/data/shapenet/shape_data
split_file: data/shapenet_split/all.csv
log_dir: /app/data/keypoints/logs

segmentations_dir: /home/taco/repos/keypoint_deformer/data/seg
