subdir: test
phase: test

split: test

# ckpt: /app/data/keypoints/logs/airplane-8kpt/checkpoints/net_final.pth
# ckpt: /app/data/keypoints/logs/autumn-waterfall-200/checkpoints/net_final.pth
ckpt: /app/data/keypoints/logs/efficient-salad-26/checkpoints/net_19100.pth

n_workers: 8
batch_size: 16

load_mesh: True


segmentations_dir: /home/taco/repos/keypoint_deformer/data/seg
